### PR TITLE
Click logo, redirect to home page

### PR DESCRIPTION
**Pull request by Abkt2001**

### CODE REVIEW

**Review by SourabhSaraswat-191939 — COMMENTED** [review]
There is no need to use href="/" on "ByteCodeAboutUs.vue " because the About section is already on the home route. So I think it should not be there.

**Review by SourabhSaraswat-191939 — CHANGES_REQUESTED** [review]
There is no need to use href="/" on "ByteCodeAboutUs.vue " because the About section is already on the home route. So I think it should not be there.

**Comment by Abkt2001** [comment]
I think it should be there because in the case of mobile view if any user wants to see the upper part of the page then just click the logo and reach there no need to scroll.
Note:- Better User Experience

**Comment by SourabhSaraswat-191939** [comment]
If we do this then it only blinks (or may be not) a page and scroll will be at the place at which it is as we are working on components in Vue.Js . So to see the upper part of the page on click it will be good to reference it with id:
       ```
               <a href="#Id"></a>
       ```
Here `Id` is the id of the part to which you want to scroll.


After this still it doesn't make the user experience easy because the about section is just below the Home (Intro) section of home page.
But still, you can make a change if you want. There is no loss in applying that changes. So I will suggest you to make a reference with `Id` as mentioned above.

**Comment by SourabhSaraswat-191939** [comment]
I appreciate your efforts, but there is an issue here that the changes you did are perfect for normal HTML, CSS, Js because on this `<a href="/">` method your URL will change and your page will completely reload again as per route.  But as we are working on Vue.Js , we work on Web Apps (Single Page Application). So in this, we use framework feature i.e. there will be no page reload on route change.

**Comment by Abkt2001** [comment]
Can you suggest what should I do. Or what changes I should do here.

**Review by SourabhSaraswat-191939 — CHANGES_REQUESTED** [review]
So to make its route change without refreshing the page you can use router link :

Like to create link on below image code:
   ```
      <center><img id="logo_img" :src="logo" /></center>
   ```
In Vue.Js, You just have to enclose it within `<router-link>` tag rather than that of `<a>` tag, as mentioned below:
   ```
      <center><router-link :to="{ path: '/' }"><img id="logo_img" :src="logo" /></router-link></center>
   ```

Similarly you can do this for all changes you made.

**Comment by Abkt2001** [comment]
Thanks for your suggestions. I will change all the files according to vue.js.

**Comment by SourabhSaraswat-191939** [comment]
Best Of Luck 👍🏻

**Pull request merged**
